select * from emp;
INSERT INTO emp (EMPNO, ENAME, JOB) VALUES (1, 'KIM', 'MANAGER');
SELECT * FROM emp;
select sysdate from dual;
SELECT * FROM EMP
WHERE JOB = 'MANAGER';
SELECT ENAME, SAL FROM EMP
WHERE SAL>2000;
SELECT DISTINCT JOB FROM EMP; 
SELECT JOB FROM EMP;
SELECT DISTINCT JOB, DEPTNO FROM EMP;
SELECT JOB, DEPTNO FROM EMP;
SELECT * FROM EMP 
WHERE SAL >= 3000;
SELECT ENAME, SAL, DEPTNO 
FROM EMP;
SELECT ENAME, SAL 
FROM EMP 
WHERE DEPTNO = 20;
SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT JOB, DEPTNO fROM EMP;
SELECT JOB, DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;
SELECT DISTINCT SAL FROM EMP;
SELECT DISTINCT JOB, DEPTNO, SAL FROM EMP;