SELECT * FROM EMP;
SELECT EMPNO AS "사원번호" FROM EMP;
SELECT ENAME AS "사원이름" FROM EMP;
SELECT JOB AS "직업" FROM EMP;
SELECT MGR AS "직속상관-사원번호" FROM EMP;
SELECT HIREDATE AS "회사입사일" FROM EMP;
SELECT SAL AS "월급" FROM EMP;
SELECT COMM AS "상여금" FROM EMP;
SELECT DEPTNO AS "부서번호" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업" , COMM AS "상여금" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", HIREDATE AS "회사입사일" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름",  MGR AS "직속상관-사원번호" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", DEPTNO AS "부서번호" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업" , HIREDATE AS "회사입사일" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "사원이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE AS "회사입사일" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE AS "회사입사일", SAL AS "급여", COMM AS "상여금", DEPTNO AS "부서번호" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함", DEPTNO AS "부서번호" FROM EMP;
SELECT * FROM EMP
ORDER BY SAL DESC;
SELECT * FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;
SELECT * FROM EMP
ORDER BY HIREDATE DESC;
SELECT * FROM EMP 
WHERE DEPTNO = 10 AND SAL >= 2000;
SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN'; 
SELECT * FROM EMP WHERE JOB = 'CLERK' OR JOB = 'MANAGER';
SELECT * FROM EMP WHERE (DEPTNO = 10 OR DEPTNO =20) AND SAL > 2000;
SELECT ENAME AS "이름", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT * FROM EMP WHERE ENAME < 'MILLER';
SELECT * FROM EMP WHERE JOB = 'CLERK' OR JOB = 'MANAGER';
SELECT * FROM EMP WHERE DEPTNO IN (10, 20, 30); 
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 3000;
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%AM%';
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT ENAME FROM EMP WHERE JOB = 'MANAGER'
UNION
SELECT ENAME FROM EMP WHERE DEPTNO = 10;
SELECT ENAME FROM EMP WHERE JOB = 'MANAGER'
UNION ALL
SELECT ENAME FROM EMP WHERE DEPTNO = 10;
SELECT ENAME FROM EMP WHERE DEPTNO = 10
MINUS
SELECT ENAME FROM EMP WHERE JOB = 'MANAGER';
SELECT ENAME FROM EMP WHERE JOB = 'CLERK' INTERSECT SELECT ENAME FROM EMP WHERE DEPTNO = 20;
SELECT UPPER(ENAME) FROM EMP;
SELECT SUM(SAL) FROM EMP;
SELECT AVG(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP;
SELECT MIN(SAL) FROM EMP;
SELECT COUNT(*) FROM EMP;
SELECT ENAME, UPPER(ENAME) AS 대문자, LOWER(ENAME) AS 소문자 FROM EMP;
SELECT * FROM EMP WHERE ENAME = TRIM(UPPER(' smith '));
SELECT ENAME, HIREDATE FROM EMP WHERE SUBSTR(HIREDATE, 1, 2) = '81';
SELECT ENAME, INSTR(ENAME, 'A') AS A의위치 FROM EMP;
SELECT ENAME, LENGTH(ENAME) AS 이름길이 FROM EMP WHERE LENGTH(ENAME) = 5;
SELECT JOB, INSTR(JOB, 'A') AS A의위치 FROM EMP;
SELECT JOB, LENGTH(JOB) AS 직업명길이 FROM EMP WHERE LENGTH(JOB) = 7;
SELECT * FROM EMP ORDER BY SAL ASC;
SELECT * FROM EMP ORDER BY SAL DESC;
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;
SELECT ENAME, SAL FROM EMP ORDER BY SAL;
SELECT * FROM EMP ORDER BY HIREDATE DESC;
SELECT * FROM EMP ORDER BY DEPTNO ASC, ENAME DESC;
SELECT * FROM EMP ORDER BY COMM DESC, SAL ASC;
SELECT ENAME, DEPTNO, SAL FROM EMP ORDER BY SAL DESC;
SELECT * FROM SALGRADE ORDER BY GRADE ASC, HISAL DESC;
SELECT * FROM EMP WHERE SAL >= 2000;
SELECT * FROM EMP WHERE HIREDATE > '1981-02-20' ORDER BY HIREDATE DESC;
SELECT * FROM EMP WHERE DEPTNO != 10;
SELECT * FROM EMP WHERE DEPTNO = 30 AND SAL >= 1600;
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'ANALYST';
SELECT * FROM EMP WHERE (DEPTNO = 10 OR DEPTNO = 20) AND JOB = 'CLERK';
SELECT * FROM EMP WHERE SAL >= 1500 AND COMM IS NOT NULL;
SELECT * FROM EMP WHERE JOB = 'SALESMAN' OR SAL >= 3000;
SELECT * FROM EMP WHERE DEPTNO IN (10, 20, 30) AND SAL >= 2000;
SELECT * FROM EMP WHERE JOB = 'CLERK' AND SAL BETWEEN 1000 AND 1500;
SELECT ENAME, JOB FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE DEPTNO = 10 AND (JOB != 'MANAGER' OR MGR IS NULL);
SELECT * FROM EMP WHERE ENAME = UPPER('scott');
SELECT * FROM EMP WHERE LENGTH(ENAME) >= 5;
SELECT * FROM EMP WHERE INSTR(JOB, 'S') > 0;